---
- name: remote server must pull this default yml from github and run on itself
  hosts: localhost
  connection: local
  become: true
  tasks:
    - import_tasks: tasks/packages.yml
    - import_tasks: cronjob.yml


